export const applications: IApplication[] = [
  {
    id: "1",
    title: "DaoDesk",
    category: ["DeFi", "DAO"],
    description: "Sed tempor vitae urna quis imperdiet. In vehicula cursus sodales. Nullam consequat massa id rhoncus tristique. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur interdum, tellus in tincidunt maximus, nibh risus viverra sapien, id fermentum odio mi vel dolor. Vivamus vitae diam sit amet nibh elementum suscipit non sed odio. Donec porttitor sollicitudin turpis, ultricies consequat velit gravida nec.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/daodesk",
    user: "",
    screenshots: [
      "https://i.imgur.com/nh12vjO.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: true,
    createdBy: "0xd836D2c9a6e014c2056093BdC4FaA7343CAe80c9",
  },
  {
    id: "2",
    title: "TokenSquare",
    category: ["DeFi", "DAO"],
    description:
      "Vestibulum tempor feugiat congue. Donec pretium eros enim. Fusce luctus velit consequat, tristique diam at, pulvinar nibh.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/TokenSquare",
    user: "",
    screenshots: [
      "https://i.imgur.com/hK2Narh.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: true,
    createdBy: "0xd836D2c9a6e014c2056093BdC4FaA7343CAe80c9",
  },
  {
    id: "3",
    title: "CryptoCouncil",
    category: ["DeFi", "DAO"],
    description:
      "Sed tempor vitae urna quis imperdiet. In vehicula cursus sodales. Nullam consequat massa id rhoncus tristique.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/CryptoCouncil",
    user: "",
    screenshots: [
      "https://i.imgur.com/7cdCRdQ.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: true,
    createdBy: "0xd836D2c9a6e014c2056093BdC4FaA7343CAe80c9",
  },
  {
    id: "4",
    title: "DaoDesk",
    category: ["DeFi", "DAO"],
    description:
      "Sed tempor vitae urna quis imperdiet. In vehicula cursus sodales. Nullam consequat massa id rhoncus tristique.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/daodesk",
    user: "",
    screenshots: [
      "https://i.imgur.com/nh12vjO.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: false,
    createdBy: "",
  },
  {
    id: "5",
    title: "TokenSquare",
    category: ["DeFi", "DAO"],
    description:
      "Vestibulum tempor feugiat congue. Donec pretium eros enim. Fusce luctus velit consequat, tristique diam at, pulvinar nibh.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/TokenSquare",
    user: "",
    screenshots: [
      "https://i.imgur.com/hK2Narh.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: false,
    createdBy: "",
  },
  {
    id: "6",
    title: "CryptoCouncil",
    category: ["DeFi", "DAO"],
    description:
      "Sed tempor vitae urna quis imperdiet. In vehicula cursus sodales. Nullam consequat massa id rhoncus tristique.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/CryptoCouncil",
    user: "",
    screenshots: [
      "https://i.imgur.com/7cdCRdQ.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: false,
    createdBy: "",
  },
  {
    id: "7",
    title: "DaoDesk",
    category: ["DeFi", "DAO"],
    description:
      "Sed tempor vitae urna quis imperdiet. In vehicula cursus sodales. Nullam consequat massa id rhoncus tristique.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/daodesk",
    user: "",
    screenshots: [
      "https://i.imgur.com/nh12vjO.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: false,
    createdBy: "",
  },
  {
    id: "8",
    title: "TokenSquare",
    category: ["DeFi", "DAO"],
    description:
      "Vestibulum tempor feugiat congue. Donec pretium eros enim. Fusce luctus velit consequat, tristique diam at, pulvinar nibh.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/TokenSquare",
    user: "",
    screenshots: [
      "https://i.imgur.com/hK2Narh.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: false,
    createdBy: "",
  },
  {
    id: "9",
    title: "CryptoCouncil",
    category: ["DeFi", "DAO"],
    description:
      "Sed tempor vitae urna quis imperdiet. In vehicula cursus sodales. Nullam consequat massa id rhoncus tristique.",
    applicationUrl: "https://daodesk.org",
    repoUrl: "https://github.com/daodesk/CryptoCouncil",
    user: "",
    screenshots: [
      "https://i.imgur.com/7cdCRdQ.png",
      "https://i.imgur.com/samibbK.png",
      "https://i.imgur.com/zVIB9Em.png",
    ],
    isEditorsPick: false,
    createdBy: "",
  },
];

export const searchData = {
  trendingNow: ["DaoDesk", "TokenSquare", "CryptoCouncil"],
  editorPicks: ["Governance Hub", "Blockboard", "ChainCouncil"],
  categories: [
    "Tokenize",
    "Votetok",
    "Category",
    "Token Plus",
    "Toknik",
    "Collabtok",
  ],
};
